<a href="https://colab.research.google.com/github/HarnoorKaur812/Deep-Learning/blob/main/Assign_4_dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('abalone.data',header=None)

In [3]:
data.columns=['Sex','Length','Diameter','Height','Whole weight','Shucked weight','Viscera weight','Shell weight','Rings']

In [4]:
data.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [5]:
data.shape[0]     #No. of rows

4177

In [6]:
data.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')

In [7]:
data['y']=data['Rings']+1.5
data.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings,y
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15,16.5
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7,8.5
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9,10.5
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10,11.5
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7,8.5

In [8]:
x=np.column_stack((data['Length']*data['Height'],data['Diameter'],data['Shell weight']))
y=data['y'].values

In [9]:
#Feature 1: (Length*Height)
#This feature approximates body volume contribution.
#Since abalone age is related to growth, a size-based interaction

#Feature 2: (Diameter)
#Represents overall body width.
#Together with length,it reflects general body size and growth stage.

#Feature 3: (Shell weight)
#Shell weight increases as the abalone ages.

In [10]:
s=int(0.8*len(x))
x_train=x[:s]
y_train=y[:s]
x_test=x[s:]
y_test=y[s:]

x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3341, 3), (836, 3), (3341,), (836,))

In [11]:
mean=x_train.mean(axis=0)
std=x_train.std(axis=0)
print('Mean =',mean,',std =',std)

Mean = [0.07702828 0.40686321 0.23851092] ,std = [0.03531722 0.09974087 0.14113385]

In [12]:
#Normalisation
x_train=(x_train-mean)/std
x_test=(x_test-mean)/std

In [13]:
w=np.zeros(x_train.shape[1])
b=0.0

def forward(x,w,b):
    y_pred=np.dot(x,w)+b
    return y_pred

#parameters are w,b
#No. of parameters 4

In [14]:
y_pred=forward(x_train, w, b)
x_train.shape,w.shape,y_pred.shape

((3341, 3), (3,), (3341,))

In [15]:
def mse(y,y_pred):
  loss=np.mean((y-y_pred)**2)
  return loss

In [16]:
def grad_dw(x,y,y_pred):
  dw=(2/len(y))*np.dot(x.T,(y_pred-y))
  return dw

def grad_db(y,y_pred):
  db=(2/len(y))*np.sum(y_pred-y)
  return db

In [20]:
lr=0.001
epoch=1000

for e in range(epoch):
  y_pred=forward(x_train,w,b)
  loss=mse(y_train,y_pred)
  dw=grad_dw(x_train,y_train,y_pred)
  db=grad_db(y_train,y_pred)
  w=w-lr*dw
  b=b-lr*db

  if e%100==0:
    print("Epoch :",e,"Loss :",loss)

Epoch : 0 Loss : 9.260579635402907
Epoch : 100 Loss : 8.450011144020836
Epoch : 200 Loss : 7.90428248923161
Epoch : 300 Loss : 7.536099981754483
Epoch : 400 Loss : 7.286974232693487
Epoch : 500 Loss : 7.117712589276016
Epoch : 600 Loss : 7.002051123434335
Epoch : 700 Loss : 6.922388554937001
Epoch : 800 Loss : 6.866928021167416
Epoch : 900 Loss : 6.827761996709295

In [21]:
y_test_pred=forward(x_test,w,b)
print('MSE for test data : ',mse(y_test,y_test_pred))
print('MAE for test data : ',np.mean(np.abs(y_test-y_test_pred)))

MSE for test data :  4.915412791772761
MAE for test data :  1.6506749938497673

In [22]:
for i in range(5):
  print('True Age :',y_test[i])
  print('Predicted Age :',y_test_pred[i])
  print('Error :',y_test[i]-y_test_pred[i],'\n')

True Age : 13.5
Predicted Age : 10.665471487361359
Error : 2.8345285126386415

True Age : 15.5
Predicted Age : 9.455599910068141
Error : 6.044400089931859

True Age : 14.5
Predicted Age : 9.934710973876083
Error : 4.565289026123917

True Age : 14.5
Predicted Age : 10.903403286137207
Error : 3.596596713862793

True Age : 13.5
Predicted Age : 11.031744243671424
Error : 2.468255756328576